production: &defaults
  adapter: postgresql
  encoding: unicode
  database: Google_Circles_development
  pool: 5
  username: enbake
  password: enbake

development:
  <<: *defaults
  database: Google_Circles_development

test:
  <<: *defaults
  database: Google_Circles_test
